# NumPy



## Import NumPy

In [ ]:
import numpy as np

## 1d array construction

### From a list

In [ ]:
list_a = [2, 7, 4]
arr_a = np.array(list_a)
arr_a

array([2, 7, 4])

### Using NumPy method (1): ones, zeros, arange, linspace

In [ ]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_range = np.arange(15)
arr_range


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr_lins = np.linspace(0, 1, num = 101)
arr_lins 

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

### Using NumPy method (2): random numbers

- to generate random numbers, use `np.random.*()`
    - uniform: `np.random.rand()`
    - normal distribution: `np.random.randn()`
    - random integer: `np.random.randint()`
- To make the outcome reproducible, use `np.random.seed()`

In [ ]:
np.random.seed(42)
arr_unif = np.random.rand(10)
arr_unif

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [ ]:
np.random.randn(10)

array([-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227,
       -1.91328024, -1.72491783, -0.56228753, -1.01283112,  0.31424733])

In [ ]:
np.random.randint(low = 0, high = 101, size = 20)

array([ 91,  59,  79,  14,  61,  61,  46,  61,  50,  54,  63,   2, 100,
        50,   6,  20,  72,  38,  17,   3])

## 1d array indexing

- There are a number of ways to subset the array
  1. Use index slicing `:`
    - similar to list slicing
  2. Boolean logic
  3. Use list to supply indexes (fancy indexing)



In [ ]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[-3:]

array([12, 13, 14])

In [ ]:
bool_arr = arr > 6
bool_arr
arr[bool_arr]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr[arr > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.random.seed(41)
arr_int = np.random.randint(0, 20, 10)
arr_int

array([ 0,  3, 12,  2, 16,  1, 19, 13, 12,  3])

In [ ]:
arr_int[[3, 5, 7]]

array([ 2,  1, 13])

## 2d array construction

Again, there are several ways to generate

1. Create directly from a nested list
2. Reshape numpy array
3. Assign shape when you use numpy array creation methods (e.g. `zeros()`)

### Create directly from a nested list

In [ ]:
list_nested = [[1, 2, 3], [6, 7, 8], [10, 11, 12]]
list_nested
list_2d = np.array(list_nested)
list_2d

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [10, 11, 12]])

### Reshape numpy array

In [ ]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr_reshaped = arr.reshape(5, 3)

In [ ]:
arr_unif = np.random.rand(20)
arr_unif_2d = arr_unif.reshape(4, 5)
arr_unif_2d

array([[0.70297401, 0.83393912, 0.80197789, 0.17902873, 0.46033005],
       [0.69687815, 0.87372662, 0.51323781, 0.23917082, 0.03684428],
       [0.13273989, 0.39575107, 0.72397414, 0.50666758, 0.68372933],
       [0.56790823, 0.42265669, 0.24581504, 0.69734101, 0.10965883]])

### Assign shape (e.g. zeros())

In [ ]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 2d array indexing

- Basically it works in the same way as 1d array
  - `:`
  - Boolean
  - Fancy

In [ ]:
arr_reshaped

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr_reshaped[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr_reshaped[-2:]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr_reshaped[1:3, 1]

array([4, 7])

In [ ]:
arr_reshaped[1:3, 1:2]

array([[4],
       [7]])

In [ ]:
arr_reshaped[arr_reshaped < 5]

array([0, 1, 2, 3, 4])

In [ ]:
arr_reshaped[[1, 3]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [ ]:
arr_reshaped[:, [0, 2]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11],
       [12, 14]])

In [ ]:
arr_reshaped[[1, 4], [0, 2]]

array([ 3, 14])

In [ ]:
arr_reshaped[[1,4]][:, [0, 2]]

array([[ 3,  5],
       [12, 14]])

## NumPy array operations

- Arithmetic operations `+`, `-`, `*`...
- Functions
- See how the broadcasting works




In [34]:
arr_a = np.arange(5)
arr_b = np.arange(5, 10)

In [35]:
arr_a

array([0, 1, 2, 3, 4])

In [36]:
arr_b

array([5, 6, 7, 8, 9])

In [37]:
arr_a + arr_b

array([ 5,  7,  9, 11, 13])

In [39]:
arr_a - arr_b

array([-5, -5, -5, -5, -5])

In [40]:
arr_a * arr_b

array([ 0,  6, 14, 24, 36])

In [41]:
arr_a / arr_b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [42]:
arr_b + 3

array([ 8,  9, 10, 11, 12])

In [43]:
arr_2d = np.arange(10).reshape(2, 5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr_2d * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [45]:
arr_2d + arr_a

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [46]:
arr_2d * arr_a

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36]])

In [47]:
np.mean(arr_2d)

4.5

In [48]:
np.mean(arr_2d, axis = 0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [49]:
np.mean(arr_2d, axis = 1)

array([2., 7.])

In [52]:
np.max(arr_2d, axis = 1)

array([4, 9])